### ISSUE TITLE
Caching issue on Broncos Sack Tracker

### ISSUE THREAD

**Issue by danielboniface** [denverpost/stat-tracker#12]
The Broncos Sack Tracker was displaying data through Week 2 when I checked it today. I had to do a Ctrl + F5 to hard refresh. It then displayed data from Week 3.

Please address this caching issue since most users will not know to do a hard refresh.

**Comment by freejoe76** [comment]
Fixed. Changed the iframe URL to point to the URL plus the "?20150928" query parameter.

**Comment by danielboniface** [comment]
Thanks @freejoe76
