### ISSUE TITLE
Add functionality to Broncos Sack Tracker, tracking individual players

### ISSUE THREAD

**Issue by danielboniface** [denverpost/stat-tracker#8]
We would like to add to the sack tracker the ability to break down sacks by player, so that at quick glance users can see team sack leaders. I am picturing a second chart/graph below the first one that shows the season sack totals by player.

**Comment by freejoe76** [comment]
@danielboniface can you get me a list of all the Broncos players that could get sacks this season?

**Comment by danielboniface** [comment]
@freejoe76  I can get you that list. We have the data available in .xml format via SportsDirect. Should I create a new issue to have the sack tracker update live via those .xml files?

**Comment by danielboniface** [comment]
@freejoe76 Here's the list of defensive players via: http://denverpost.sportsdirectinc.com/football/nfl-teams.aspx?page=/data/nfl/teams/rosters/roster21.html

LINEBACKERS
Player  Num Height  Weight  DOB
Barrett, Shaquil    48  6'2"    250 lbs 11/17/92
Davis, Todd 51  6'1"    230 lbs 5/17/92
Marshall, Brandon   54  6'1"    250 lbs 9/10/89
McCray, Lerentee    55  6'3"    249 lbs 8/26/90
Miller, Von 58  6'3"    250 lbs 3/26/89
Nelson, Corey   52  6'1"    226 lbs 4/22/92
Ray, Shane  56  6'3"    245 lbs 5/18/93
Trevathan, Danny    59  6'1"    240 lbs 3/24/90
Ware, Demarcus  94  6'4"    258 lbs 7/31/82

CORNERBACKS
Player  Num Height  Weight  DOB
Doss, Lorenzo   37  5'11"   187 lbs 4/22/94
Harris, Chris   25  5'10"   199 lbs 6/18/89
Roby, Bradley   29  5'11"   194 lbs 5/1/92
Talib, Aqib 21  6'1"    205 lbs 2/13/86
Webster, Kayvon 36  5'11"   198 lbs 2/1/91

SAFETIES
Player  Num Height  Weight  DOB
Bolden, Omar    31  5'10"   195 lbs 12/20/88
Bruton Jr., David   30  6'2"    217 lbs 7/23/87
Bush, Josh  20  5'11"   205 lbs 3/5/89
Stewart, Darian 26  5'11"   214 lbs 8/4/88
Ward, T.J.  43  5'10"   200 lbs 12/12/86

NOSE TACKLES
Player  Num Height  Weight  DOB
Austin Jr., Marvin  76  6'2"    312 lbs 1/10/89
Kilgo, Darius   98  6'3"    319 lbs 12/14/91
Williams, Sylvester 92  6'2"    313 lbs 11/21/88

DEFENSIVE ENDS
Player  Num Height  Weight  DOB
Anunike, Kenny  91  6'5"    275 lbs 5/22/90
Jackson, Malik  97  6'5"    293 lbs 1/11/90
Smith, Antonio  90  6'3"    290 lbs 10/21/81
Walker, Vance   96  6'2"    305 lbs 4/26/87
Wolfe, Derek    95  6'5"    285 lbs 2/24/90

**Comment by freejoe76** [comment]
Thanks @danielboniface. Do all those positions have the potential to sack the QB?

**Comment by danielboniface** [comment]
@freejoe76 Anyone on defense could, in theory, sack the QB. I think the best way to handle this is if their sack total is 0, they are not displayed.

**Comment by freejoe76** [comment]
Right. Which positions are most likely to sack the QB?

**Comment by danielboniface** [comment]
Linebackers get the most. Defensive ends/nose tackles get some. Then cornerbacks and safeties pick up one here or there (if they bring them on a blitz)

**Comment by freejoe76** [comment]
Done and launched ( http://www.denverpost.com/broncos/ci_28793554/denver-broncos-sack-tracker ). It's administered via a new tab on the SPORTS spreadsheet.
